#include <MsTimer2.h>

enum events {STATE_CHANGE = 1, CLICK, LONG_PRESS, ENC_UPDATE, THERM_UPDATE, POWER_CTRL_UPDATE, TEMP_CTRL_UPDATE, BB_UPDATE, SELECT_NEW_STATE};
enum states {OFF, POWER_CTRL, TEMP_CTRL, MENU, NUM_STATES};

void sm_event_send (int, int);
